#
#   Copyright 2015 Pixar
#
#   Licensed under the Apache License, Version 2.0 (the "Apache License")
#   with the following modification; you may not use this file except in
#   compliance with the Apache License and the following modification to it:
#   Section 6. Trademarks. is deleted and replaced with:
#
#   6. Trademarks. This License does not grant permission to use the trade
#      names, trademarks, service marks, or product names of the Licensor
#      and its affiliates, except as required to comply with Section 4(c) of
#      the License and to reproduce the content of the NOTICE file.
#
#   You may obtain a copy of the Apache License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the Apache License with the above modification is
#   distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#   KIND, either express or implied. See the Apache License for the specific
#   language governing permissions and limitations under the Apache License.
#
language: cpp

os:
    - linux
    - osx

osx_image: xcode9

sudo: required
dist: trusty

compiler:
    - gcc
    - clang

branches:
  only:
   - master
   - dev

matrix:

    # On Linux build with gcc and on OSX build with clang
    exclude:
        - os: osx
          compiler: gcc
        - os: linux
          compiler: clang

# build environment
before_script:
   - if [ $TRAVIS_OS_NAME == osx ] ; then
        echo "before_script on OSX" ;
     elif [ $TRAVIS_OS_NAME == linux ] ; then
        echo "before_script on Linux" ;
        source build_scripts/travis_before_script_linux.sh ;
     fi

script:
   - if [ $TRAVIS_OS_NAME == osx ] ; then
        echo "script on OSX" ;
        build_scripts/travis_script_osx.sh ;
     elif [ $TRAVIS_OS_NAME == linux ] ; then
        echo "script on Linux" ;
        source build_scripts/travis_script_linux.sh ;
     fi
