#
#   Copyright 2015 Pixar
#
#   Licensed under the Apache License, Version 2.0 (the "Apache License")
#   with the following modification; you may not use this file except in
#   compliance with the Apache License and the following modification to it:
#   Section 6. Trademarks. is deleted and replaced with:
#
#   6. Trademarks. This License does not grant permission to use the trade
#      names, trademarks, service marks, or product names of the Licensor
#      and its affiliates, except as required to comply with Section 4(c) of
#      the License and to reproduce the content of the NOTICE file.
#
#   You may obtain a copy of the Apache License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the Apache License with the above modification is
#   distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#   KIND, either express or implied. See the Apache License for the specific
#   language governing permissions and limitations under the Apache License.
#
language: cpp

branches:
  only:
   - master
   - dev

# build environment
before_script:
   # as of 4/28/2015, travis worker has pre-installed cmake 2.8.7.
   # opensubdiv needs 2.8.8 or later.
   # get the latest cmake from PPA
   - cmake --version
   - sudo add-apt-repository --yes ppa:dcthomp/smtk
   - sudo apt-get update -qq
   # remove existing cmake
   - sudo dpkg -r cmake cmake-data
   # install newer version
   - sudo apt-get install cmake
   - cmake --version

   # install GL related libs from utopic
   - sudo add-apt-repository 'deb http://us.archive.ubuntu.com/ubuntu/ utopic main restricted universe multiverse'
   - sudo add-apt-repository 'deb http://us.archive.ubuntu.com/ubuntu/ utopic-updates main restricted universe multiverse'
   - sudo apt-get update -qq
   # install glut and xxf86vm (for GL libs)
   - sudo apt-get install freeglut3-dev
   - sudo apt-get install libxxf86vm-dev
   # install GLEW
   - sudo apt-get install libglew-dev
   # install GLFW3
   - sudo apt-get install libglfw3-dev

   # hopefully we'd like to test basic imaging tests too, using X virtual framebuffer
   # (not working now)
   - sudo apt-get install xvfb

script:
   - mkdir build && cd build
   - cmake -DNO_TBB=1 -DNO_OMP=1 -DNO_CUDA=1 -DNO_OPENCL=1 -DNO_MAYA=1 -DNO_PTEX=1 -DNO_GLTESTS=1 -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
   - make
   - make test

