//
//   Copyright 2015 Pixar
//
//   Licensed under the Apache License, Version 2.0 (the "Apache License")
//   with the following modification; you may not use this file except in
//   compliance with the Apache License and the following modification to it:
//   Section 6. Trademarks. is deleted and replaced with:
//
//   6. Trademarks. This License does not grant permission to use the trade
//      names, trademarks, service marks, or product names of the Licensor
//      and its affiliates, except as required to comply with Section 4(c) of
//      the License and to reproduce the content of the NOTICE file.
//
//   You may obtain a copy of the Apache License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the Apache License with the above modification is
//   distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//   KIND, either express or implied. See the Apache License for the specific
//   language governing permissions and limitations under the Apache License.
//

#ifndef FAR_END_CAP_REGULAR_PATCH_FACTORY_H
#define FAR_END_CAP_REGULAR_PATCH_FACTORY_H

#include "../far/patchTablesFactory.h"
#include "../far/protoStencil.h"
#include "../vtr/level.h"

namespace OpenSubdiv {
namespace OPENSUBDIV_VERSION {

namespace Far {

class TopologyRefiner;

/// \brief A specialized factory to gather Regular B-spline control vertices
///
class EndCapRegularPatchFactory {

public:
    // XXXX need to add support for face-varying channel stencils

    /// \brief This factory accumulates vertex for regular end cap
    ///
    /// @param refiner                TopologyRefiner from which to generate patches
    ///
    /// @param shareBoundaryVertices  Use same boundary vertices for neighboring
    ///                               patches. It reduces the number of stencils
    ///                               to be used.
    ///
    EndCapRegularPatchFactory(TopologyRefiner const & refiner);

    ~EndCapRegularPatchFactory();

    /// \brief Returns a patch type for \a patchTag generated by this factory.
    ///
    /// @param patchTag    identified tag information for the patch
    ///
    PatchDescriptor::Type GetPatchType(PatchTablesFactoryBase::PatchFaceTag const &patchTag) const;

    /// \brief Returns an end patch vertex indices for \a faceIndex.
    ///
    /// @param level            vtr refinement level
    ///
    /// @param faceIndex        vtr faceIndex at the level
    ///
    /// @param levelPatchTags   Array of patchTags for all faces in the level
    ///
    /// @param levelVertOffset  relative offset of patch vertex indices
    ///
    ConstIndexArray GetTopology(Vtr::Level const& level, Index faceIndex,
                                PatchTablesFactoryBase::PatchFaceTag const * levelPatchTags,
                                int levelVertOffset);

    /// After all the gregory basis vertices have been collected, factorize
    /// their stencils with given stencil table and create new stencil table.
    ///
    /// @param baseStencils  source stencil table
    ///
    /// @param append        if true, returns concatinated stencil table which
    ///                      also includes source stencil table at the front.
    ///
    /// @param permute       index permutation table (optional)
    ///
    StencilTables const * CreateVertexStencilTables(
        StencilTables const *baseStencils, bool append);
    StencilTables const * CreateVaryingStencilTables(
        StencilTables const *baseStencils, bool append);

private:

    StencilTables const *createStencilTables(StencilAllocator &alloc,
                                             StencilTables const *baseStencils,
                                             bool append);

    struct Context;
    Context *_context;
};

} // end namespace Far

} // end namespace OPENSUBDIV_VERSION
} // end namespace OpenSubdiv

#endif  // FAR_END_CAP_GREGORY_BASIS_PATCH_FACTORY_H
